In [2]:
import torch
import numpy as np
import pandas as pd

In [3]:
feat_map = torch.load('../../data/Chipseq_data/FeatMap.pt')
feat_map = {v: k for k, v in feat_map.items()}

In [42]:
nonormalznull = pd.read_csv('commontopten/nonormalznull/YY1 common sequences with intersections.tsv', sep='\t')
dualmodel = pd.read_csv('commontopten/dualmodel/YY1 common sequences with intersections.tsv', sep='\t')
gnull = pd.read_csv('commontopten/gnull/YY1 common sequences with intersections.tsv', sep='\t')
znull = pd.read_csv('commontopten/znull/YY1 common sequences with intersections.tsv', sep='\t')

In [43]:
models = {}

In [45]:
models[0] = nonormalznull
models[1] = dualmodel
models[2] = gnull
models[3] = znull

In [47]:
for i in range(len(models)):
    seqs = []
    for index, row in models[i].iterrows():
        seq = row['Sequence']
        seqs.append(seq)
    models[i] = seqs

In [51]:
def matrix_generator(models):
    union_matrix = np.zeros((len(models), len(models)), dtype=int)
    for i, j in np.ndindex(union_matrix.shape):
        union_matrix[i, j] = sum(1 for oneseq in models[i] for otherseq in models[j] if oneseq == otherseq)
    return union_matrix

In [52]:
Modelmatrix = matrix_generator(models)
print(Modelmatrix)

[[21  0  3  2]
 [ 0 37  1  2]
 [ 3  1 25  9]
 [ 2  2  9 20]]


In [53]:
np.set_printoptions(threshold=sys.maxsize)

In [54]:
np.savetxt('Modelmatrix.csv', Modelmatrix, delimiter=',')