In [27]:
import torch
import sys
sys.path.append('../../data_processing')
sys.path.append('../../model')
sys.path.append('../../../data')
import CNN, CNN_multimodal, CNN_LSTM
import TF_data_loader
from torch.utils import data as D
import numpy as np
from sklearn.metrics import PrecisionRecallDisplay, RocCurveDisplay
from sklearn.metrics import precision_recall_curve, average_precision_score, roc_curve, auc
import matplotlib.pyplot as plt
from tqdm.notebook import tqdm

In [28]:
feat_map = torch.load('../../../data/Chipseq_data/FeatMap.pt')
feat_map = {v: k for k, v in feat_map.items()}

In [29]:
sorted_sequence_score_topten = torch.load('sorted_sequence_score_topten.pt')

In [30]:
def matrix_generator(cell_line_index):
    union_matrix = np.zeros((len(cell_line_index), len(cell_line_index)), dtype=int)
    for i, j in np.ndindex(union_matrix.shape):
        union_matrix[i, j] = sum(1 for oneseq in cell_line_index[i] for otherseq in cell_line_index[j] if oneseq[4] == otherseq[4])
    return union_matrix

In [42]:
YY1_cell_line_index = [4, 36, 42, 53, 94, 125]
All_cell_line_index = [4, 36, 42, 53, 94, 125]

swap = [i for i in range(130) if i not in YY1_cell_line_index]
for element in swap:
    All_cell_line_index.append(element)

In [45]:
All_sequences = []
for index in All_cell_line_index:
    for cell_line in sorted_sequence_score_topten:
        if cell_line[0][0] == feat_map[index]:
            All_sequences.append(cell_line)

In [47]:
YY1_sequences = []
for index in YY1_cell_line_index:
    for cell_line in sorted_sequence_score_topten:
        if cell_line[0][0] == feat_map[index]:
            YY1_sequences.append(cell_line)

In [58]:
YY1 = matrix_generator(YY1_sequences)
print(result)

[[10  2  2  3  2  4]
 [ 2 10  3  3  3  5]
 [ 2  3 10  4  1  2]
 [ 3  3  4 10  0  3]
 [ 2  3  1  0 10  1]
 [ 4  5  2  3  1 10]]


In [50]:
np.set_printoptions(threshold=sys.maxsize)

In [55]:
All = matrix_generator(All_sequences)

In [57]:
np.savetxt('union_matrix_all.csv', All, delimiter=',')

In [59]:
np.savetxt('union_matrix_YY1.csv', YY1, delimiter=',')